/* Populate database with sample data. */

INSERT INTO ANIMALS (ID, NAME, DATE_OF_BIRTH, ESCAPE_ATTEMPTS, NEUTERED, WEIGHT_KG) VALUES (1, 'Agumon', '2020-02-03', 0, TRUE, 10.23);

INSERT INTO ANIMALS (ID, NAME, DATE_OF_BIRTH, ESCAPE_ATTEMPTS, NEUTERED, WEIGHT_KG) VALUES (2, 'Gabumon', '2018-11-15', 2, TRUE, 8.00);

INSERT INTO ANIMALS (ID, NAME, DATE_OF_BIRTH, ESCAPE_ATTEMPTS, NEUTERED, WEIGHT_KG) VALUES (3, 'Pikachu', '2021-01-07', 1, FALSE, 15.04);

INSERT INTO ANIMALS (ID, NAME, DATE_OF_BIRTH, ESCAPE_ATTEMPTS, NEUTERED, WEIGHT_KG) VALUES (4, 'Devimon', '2017-05-12', 5, TRUE, 11.00);

INSERT INTO ANIMALS (ID, NAME, DATE_OF_BIRTH, ESCAPE_ATTEMPTS, NEUTERED, WEIGHT_KG) VALUES (5, 'Charmander', '2020-02-08', 0, FALSE,-11);

INSERT INTO ANIMALS (ID, NAME, DATE_OF_BIRTH, ESCAPE_ATTEMPTS, NEUTERED, WEIGHT_KG) VALUES (6, 'Plantmon', '2022-11-15', 2, TRUE, -5.7);

INSERT INTO ANIMALS (ID, NAME, DATE_OF_BIRTH, ESCAPE_ATTEMPTS, NEUTERED, WEIGHT_KG) VALUES (7, 'Squirtle', '1993-04-02', 3, FALSE, -12.13);

INSERT INTO ANIMALS (ID, NAME, DATE_OF_BIRTH, ESCAPE_ATTEMPTS, NEUTERED, WEIGHT_KG) VALUES (8, 'Angemon', '2005-06-12', 1, TRUE, -45);

INSERT INTO ANIMALS (ID, NAME, DATE_OF_BIRTH, ESCAPE_ATTEMPTS, NEUTERED, WEIGHT_KG) VALUES (9, 'Boarmon', '2005-06-07', 7, TRUE, 20.4);

INSERT INTO ANIMALS (ID, NAME, DATE_OF_BIRTH, ESCAPE_ATTEMPTS, NEUTERED, WEIGHT_KG) VALUES (10, 'Blossom', '1998-10-13', 3, TRUE, 17);

INSERT INTO OWNERS(FULL_NAME, AGE) VALUES('Sam Smith', 34);
INSERT INTO OWNERS(FULL_NAME, AGE) VALUES('Jennifer Orwell', 19);
INSERT INTO OWNERS(FULL_NAME, AGE) VALUES('Bob', 45);
INSERT INTO OWNERS(FULL_NAME, AGE) VALUES('Melody Pond', 77);
INSERT INTO OWNERS(FULL_NAME, AGE) VALUES('Dean Winchester', 14);
INSERT INTO OWNERS(FULL_NAME, AGE) VALUES('Jodie Whittaker', 38);

INSERT INTO SPECIES(NAME) VALUES('Pokemon');
INSERT INTO SPECIES(NAME) VALUES('Digimon');

BEGIN;
UPDATE ANIMALS SET SPECIE_ID=1 WHERE NAME LIKE '%mon';
COMMIT;

BEGIN;
UPDATE ANIMALS SET SPECIE_ID=2 WHERE NAME NOT LIKE '%mon';
COMMIT;

BEGIN;
UPDATE ANIMALS SET OWNER_ID = (SELECT ID FROM OWNERS WHERE FULL_NAME = 'Sam Smith') WHERE NAME='Agumon';
COMMIT;

BEGIN;
UPDATE ANIMALS SET OWNER_ID = (SELECT ID FROM OWNERS WHERE FULL_NAME = 'Jennifer Orwell') WHERE NAME IN ('Gabumon', 'Pikachu');
COMMIT;

BEGIN;
UPDATE ANIMALS SET OWNER_ID = (SELECT ID FROM OWNERS WHERE FULL_NAME = 'Bob') WHERE NAME IN ('Plantmon', 'Devimon');
COMMIT;

BEGIN;
UPDATE ANIMALS SET OWNER_ID = (SELECT ID FROM OWNERS WHERE FULL_NAME = 'Melody Pond') WHERE NAME IN ('Charmander', 'Squirtle', 'Blossom');
COMMIT;

BEGIN;
UPDATE ANIMALS SET OWNER_ID = (SELECT ID FROM OWNERS WHERE FULL_NAME = 'Dean Winchester') WHERE NAME IN ('Angemon', 'Boarmon');
COMMIT;