/*Queries that provide answers to the questions from all projects.*/

SELECT * FROM ANIMALS WHERE NAME LIKE '%mon'

SELECT NAME FROM ANIMALS WHERE DATE_OF_BIRTH BETWEEN '2016-01-01' AND '2019-01-01';

SELECT NAME FROM ANIMALS WHERE NEUTERED=TRUE AND ESCAPE_ATTEMPTS < 3;

SELECT DATE_OF_BIRTH FROM ANIMALS WHERE NAME IN ('Agumon', 'Pikachu');

SELECT NAME, ESCAPE_ATTEMPTS FROM ANIMALS WHERE WEIGHT_KG > 10.5;

SELECT * FROM ANIMALS WHERE NEUTERED=TRUE;

SELECT * FROM ANIMALS WHERE NAME NOT IN ('Gabumon');

SELECT * FROM ANIMALS WHERE WEIGHT_KG BETWEEN 10.4 AND 17.3;

BEGIN TRANSACTION;

UPDATE ANIMALS SET SPECIES = 'unspecified';

ROLLBACK TRANSACTION;

BEGIN;

UPDATE ANIMALS SET SPECIES='DIGIMON' WHERE NAME LIKE '%mon';

UPDATE ANIMALS SET SPECIES='POKEMON' WHERE NAME NOT LIKE '%mon';

COMMIT;

BEGIN;

DELETE FROM ANIMALS;

ROLLBACK;

BEGIN;

DELETE FROM ANIMALS WHERE DATE_OF_BIRTH>'2022-01-01';

SAVEPOINT SP1;

UPDATE ANIMALS SET WEIGHT_KG = WEIGHT_KG * -1;

ROLLBACK;

BEGIN;

UPDATE ANIMALS SET WEIGHT_KG = WEIGHT_KG * -1 WHERE WEIGHT_KG < 0;

COMMIT;

How many animals are there? 
SELECT COUNT(*) FROM ANIMALS;

How many animals have never tried to escape?
SELECT COUNT(*) FROM ANIMALS WHERE ESCAPE_ATTEMPTS = 0;

What is the average weight of animals?
SELECT AVG(WEIGHT_KG) FROM ANIMALS;

Who escapes the most, neutered or not neutered animals?
SELECT MIN(NEUTERED) FROM ANIMALS;
SELECT MAX(NEUTERED) FROM ANIMALS;
SELECT MAX(ESCAPE_ATTEMPTS) FROM ANIMALS;

What is the minimum and maximum weight of each type of animal?
SELECT MIN(WEIGHT_KG) FROM ANIMALS GROUP_BY NAME;
SELECT MAX(WEIGHT_KG) FROM ANIMALS GROUP_BY NAME;

What is the average number of escape attempts per animal type of those born between 1990 and 2000?
SELECT AVG(ESCAPE_ATTEMPTS) FROM ANIMALS WHERE DATE_OF_BIRTH BETWEEN '1990-01-01' AND '2000-01-01'; 

SELECT NAME FROM ANIMALS INNER JOIN OWNERS ON ANIMALS.OWNER_ID = OWNERS.ID WHERE OWNERS.FULL_NAME = 'Melody Pond';

select animals.name from animals inner join species on animals.specie_id = species.id where species.name='Pokemon';

SELECT OWNERS.FULL_NAME, ANIMALS.NAME FROM OWNERS LEFT JOIN ANIMALS ON ANIMALS.OWNER_ID = OWNERS.ID;

SELECT species.name ,COUNT(specie_id) FROM animals JOIN species ON species.id = animals.specie_id GROUP BY species.name;

SELECT NAME FROM ANIMALS INNER JOIN OWNERS ON OWNERS.ID = ANIMALS.OWNER_ID WHERE OWNERS.FULL_NAME = 'Jennifer Orwell' AND ANIMALS.SPECIE_ID = 2;

SELECT NAME FROM ANIMALS  JOIN OWNERS ON OWNERS.ID = ANIMALS.OWNER_ID WHERE OWNERS.FULL_NAME = 'Dean Winchester' AND escape_attempts = 0;             

SELECT OWNERS.FULL_NAME, COUNT(ANIMALS.OWNER_ID) FROM OWNERS INNER JOIN ANIMALS ON OWNERS.ID = ANIMALS.OWNER_ID GROUP BY OWNERS.FULL_NAME ORDER BY (COUNT) DESC LIMIT 1;
