/* Database schema to keep the structure of entire database. */
CREATEDB VET_CLINIC;

CREATE TABLE ANIMALS (
    ID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    NAME VARCHAR(100),
    DATE_OF_BIRTH DATE,
    ESCAPE_ATTEMPTS INTEGER,
    NEUTERED BOOLEAN,
    WEIGHT_KG FLOAT
);

ALTER TABLE ANIMALS ADD SPECIES VARCHAR(50);

CREATE TABLE OWNERS (
    ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    FULL_NAME VARCHAR(60),
    AGE INT
);

CREATE TABLE SPECIES (
    ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    NAME VARCHAR(60)
);

ALTER TABLE ANIMALS DROP COLUMN SPECIES;

ALTER TABLE ANIMALS ADD SPECIE_ID INT;

ALTER TABLE ANIMALS ADD CONSTRAINT FK1 FOREIGN KEY(SPECIE_ID) REFERENCES SPECIES(ID);

ALTER TABLE ANIMALS ADD OWNER_ID INT;

ALTER TABLE ANIMALS ADD CONSTRAINT FK2 FOREIGN KEY(OWNER_ID) REFERENCES OWNERS(ID);

