/* Database schema to keep the structure of entire database. */
CREATEDB VET_CLINIC;

CREATE TABLE ANIMALS (
    ID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    NAME VARCHAR(100),
    DATE_OF_BIRTH DATE,
    ESCAPE_ATTEMPTS INTEGER,
    NEUTERED BOOLEAN,
    WEIGHT_KG FLOAT
);

ALTER TABLE ANIMALS ADD SPECIES VARCHAR(50);

CREATE TABLE OWNERS (
    ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    FULL_NAME TEXT,
    AGE INT
);

CREATE TABLE SPECIES (
    ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    NAME TEXT
);

ALTER TABLE ANIMALS DROP COLUMN SPECIES;

ALTER TABLE ANIMALS ADD SPECIE_ID INT;

ALTER TABLE ANIMALS ADD CONSTRAINT FK1 FOREIGN KEY(SPECIE_ID) REFERENCES SPECIES(ID);

ALTER TABLE ANIMALS ADD OWNER_ID INT;

ALTER TABLE ANIMALS ADD CONSTRAINT FK2 FOREIGN KEY(OWNER_ID) REFERENCES OWNERS(ID);

CREATE TABLE VETS (
    ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    NAME TEXT,
    AGE INT,
    DATE_OF_GRADUATION DATE
);

CREATE TABLE SPECIALIZATIONS (
    SPECIE_ID INT,
    CONSTRAINT SPECIE_ID FOREIGN KEY(SPECIE_ID) REFERENCES SPECIES(ID),
    VET_ID INT,
    CONSTRAINT VET_ID FOREIGN KEY(VET_ID) REFERENCES VETS(ID)
);

CREATE TABLE VISITS (
    ANIMAL_ID INT,
    CONSTRAINT ANIMAL_ID FOREIGN KEY(ANIMAL_ID) REFERENCES ANIMALS(ID),
    VET_ID INT,
    CONSTRAINT VET_ID FOREIGN KEY(VET_ID) REFERENCES VETS(ID),
    DATE_OF_VISIT DATE
);