/* Database schema to keep the structure of entire database. */
CREATEDB VET_CLINIC;

CREATE TABLE ANIMALS (
    ID INTEGER PRIMARY KEY,
    NAME VARCHAR(100),
    DATE_OF_BIRTH DATE,
    ESCAPE_ATTEMPTS INTEGER,
    NEUTERED BOOLEAN,
    WEIGHT_KG FLOAT
);

ALTER TABLE ANIMALS ADD SPECIES VARCHAR(50);

CREATE TABLE OWNERS (
    ID INT PRIMARY KEY GENERATE ALWAYS AS IDENTITY,
    FULL_NAME VARCHAR(60),
    AGE INT
);

CREATE TABLE SPECIES (
    ID INT PRIMARY KEY GENERATE ALWAYS AS IDENTITY,
    NAME VARCHAR(60)
)